//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_table
    {
        public int advertisment_id { get; set; }
        public string advertisement_name { get; set; }
        public string advertisemnet_description { get; set; }
        public string advertisement_link { get; set; }
        public string advertisement_image { get; set; }
    }
}
