//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_table
    {
        public int admin_id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
    }
}
