//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funds_table
    {
        public int funds_id { get; set; }
        public int issue_id { get; set; }
        public int user_id { get; set; }
        public int amount { get; set; }
        public System.DateTime fund_date { get; set; }
    
        public virtual user_table user_table { get; set; }
        public virtual issue_table issue_table { get; set; }
    }
}
