//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public issue_table()
        {
            this.AssignedByAdmin = new HashSet<AssignedByAdmin>();
            this.funds_table = new HashSet<funds_table>();
            this.issue_images_table = new HashSet<issue_images_table>();
            this.nearby_user_table = new HashSet<nearby_user_table>();
            this.report_table = new HashSet<report_table>();
        }
    
        public int issue_id { get; set; }
        public int user_id { get; set; }
        public string Status { get; set; }
        public string locationLatitude { get; set; }
        public string locationLongitude { get; set; }
        public string roadSize { get; set; }
        public string waterLevel { get; set; }
        public string issuePositionwrtRoad { get; set; }
        public string traffic { get; set; }
        public string isRoadBlock { get; set; }
        public string issueStatement { get; set; }
        public string Schedule { get; set; }
        public string Iswateroverflow { get; set; }
        public string roadCoverage { get; set; }
        public string Vehiclepassing { get; set; }
        public string IssueImage { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> missingDate { get; set; }
        public Nullable<System.DateTime> foundDate { get; set; }
        public int isresolved { get; set; }
        public int estimated_cost { get; set; }
        public string location_name { get; set; }
        public Nullable<System.DateTime> resolveddate { get; set; }
        public int amount_collected { get; set; }
        public int isWorkingStarted { get; set; }
        public string issueFlag { get; set; }
        public string issueType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedByAdmin> AssignedByAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<funds_table> funds_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issue_images_table> issue_images_table { get; set; }
        public virtual issue_table issue_table1 { get; set; }
        public virtual issue_table issue_table2 { get; set; }
        public virtual user_table user_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nearby_user_table> nearby_user_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_table> report_table { get; set; }
    }
}
