//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nearby_user_table
    {
        public int ui_pair_id { get; set; }
        public int user_id { get; set; }
        public int issue_id { get; set; }
    
        public virtual issue_table issue_table { get; set; }
        public virtual nearby_user_table nearby_user_table1 { get; set; }
        public virtual nearby_user_table nearby_user_table2 { get; set; }
    }
}
