//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTable
    {
        public int notification_id { get; set; }
        public string notification_text { get; set; }
        public string notification_image { get; set; }
        public string notification_title { get; set; }
        public Nullable<System.DateTime> notification_date { get; set; }
    }
}
