//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethodInfo
    {
        public string easypaisanumber { get; set; }
        public string easypaisatitle { get; set; }
        public string jazzcashnumber { get; set; }
        public string jazzcashtitle { get; set; }
        public string bankaccountnumber { get; set; }
        public string bankaccounttitle { get; set; }
    }
}
