//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_table
    {
        public int report_id { get; set; }
        public int user_id { get; set; }
        public int issue_id { get; set; }
        public string report_text { get; set; }
        public string status { get; set; }
        public string admin_reply { get; set; }
    
        public virtual user_table user_table { get; set; }
        public virtual issue_table issue_table { get; set; }
    }
}
