//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_table()
        {
            this.funds_table = new HashSet<funds_table>();
            this.issue_table = new HashSet<issue_table>();
            this.report_table = new HashSet<report_table>();
            this.ad_table = new HashSet<ad_table>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public string email_address { get; set; }
        public string contact_no { get; set; }
        public string profile_pic { get; set; }
        public string homelocatlati { get; set; }
        public string homelocatlongi { get; set; }
        public string Joblocatlati { get; set; }
        public string Joblocatlongi { get; set; }
        public int password_hash { get; set; }
        public int userrating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<funds_table> funds_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issue_table> issue_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_table> report_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ad_table> ad_table { get; set; }
    }
}
